#!/bin/bash
# Shared helpers for the demo scripts. Sourced by the entry points, never executed directly.
#
#   demo/generate-configs.sh — keys, configs and .env for the stand
#   demo/up.sh               — bring the stand up and leave it running
#   demo/record.sh           — record the failover GIF from the stand
#
# Everything the three scripts share lives here: where the demo directory is, how to
# talk to docker compose, how the mesh subnet is picked, and how to read a node's
# next hop out of the daemon's own route table.
#
# Bash 3.2 compatible — macOS still ships 3.2, so: no associative arrays, no ${var,,}.

set -euo pipefail

DEMO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$DEMO_DIR/.." && pwd)"

if [ ! -f "$REPO_ROOT/go.mod" ]; then
  echo "demo: $REPO_ROOT does not look like the nylon checkout (no go.mod)" >&2
  exit 1
fi

IMAGE="nylon-demo-node:local"
PROJECT="nylon-demo"
ENV_FILE="$DEMO_DIR/.env"
CONFIGS_DIR="$DEMO_DIR/configs"
OUTPUT_DIR="$DEMO_DIR/output"
PANES_DIR="$DEMO_DIR/panes"

NODES="alice bob charlie"
PORT=57175

# The node the recording watches: alice's next hop toward charlie flips charlie → bob → charlie.
TARGET_ID="charlie"
BACKUP_ID="bob"
TARGET_PREFIX="10.99.0.3/32"

# Alice's link to bob is shaped to this latency (see generate-configs.sh): the
# stand's topology must have one unambiguous best path, or the mesh re-selects
# routes on bridge jitter and the recording proves nothing.
BOB_LINK_DELAY_MS=20

# Subnet pool mirrored from e2e/network_allocator.go: 10.200.0.0/24 .. 10.250.255.0/24.
SUBNET_POOL_FROM=200
SUBNET_POOL_TO=250

# ── Output ───────────────────────────────────────────────────────────
info() { printf "\033[1;36m▸ %s\033[0m\n" "$*"; }
die() {
  printf "\033[1;31m✗ %s\033[0m\n" "$*" >&2
  exit 1
}
require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"
}

# ── Node tables ──────────────────────────────────────────────────────
tunnel_ip() { # <node> — address inside the mesh
  case "$1" in
  alice) echo "10.99.0.1" ;;
  bob) echo "10.99.0.2" ;;
  charlie) echo "10.99.0.3" ;;
  *) die "unknown node: $1" ;;
  esac
}

host_octet() { # <node> — last octet of the node's docker address
  case "$1" in
  alice) echo 10 ;;
  bob) echo 11 ;;
  charlie) echo 12 ;;
  *) die "unknown node: $1" ;;
  esac
}

container() { echo "$PROJECT-$1"; } # <node> → container name

upper() { echo "$1" | tr '[:lower:]' '[:upper:]'; }

# ── Docker compose ───────────────────────────────────────────────────
dc() {
  docker compose --env-file "$ENV_FILE" -f "$DEMO_DIR/docker-compose.yml" -p "$PROJECT" "$@"
}

# ── Addresses ────────────────────────────────────────────────────────
ip_to_int() { # <a.b.c.d>
  local a b c d
  IFS=. read -r a b c d <<<"$1"
  echo $(($((10#$a * 16777216)) + $((10#$b * 65536)) + $((10#$c * 256)) + 10#$d))
}

prefix_bounds() { # <cidr> — "first:last" as integers
  local addr="${1%%/*}" len="${1##*/}" first
  case "$len" in
  '' | *[!0-9]*) return 1 ;;
  esac
  [ "$len" -le 32 ] || return 1
  first="$(ip_to_int "$addr")" || return 1
  echo "$first:$((first + (1 << (32 - len)) - 1))"
}

subnet_host_ip() { # <subnet> <last-octet>
  local a b c d
  IFS=. read -r a b c d <<<"${1%%/*}"
  echo "$a.$b.$c.$2"
}

# pick_subnet — first free 10.<200..250>.<0..255>.0/24 that does not overlap any
# docker network on this daemon. Mirrors e2e/network_allocator.go.
pick_subnet() {
  local used="" pair cidr lo hi overlap s t
  for cidr in $(docker network ls -q |
    xargs -n1 docker network inspect --format '{{range .IPAM.Config}}{{.Subnet}} {{end}}' 2>/dev/null); do
    pair="$(prefix_bounds "$cidr" 2>/dev/null)" || continue
    [ -n "$pair" ] && used="$used $pair"
  done

  s=$SUBNET_POOL_FROM
  while [ "$s" -le "$SUBNET_POOL_TO" ]; do
    t=0
    while [ "$t" -le 255 ]; do
      lo="$(ip_to_int "10.$s.$t.0")"
      hi=$((lo + 255))
      overlap=0
      for pair in $used; do
        if [ "$lo" -le "${pair##*:}" ] && [ "${pair%%:*}" -le "$hi" ]; then
          overlap=1
          break
        fi
      done
      if [ "$overlap" = 0 ]; then
        echo "10.$s.$t.0/24"
        return 0
      fi
      t=$((t + 1))
    done
    s=$((s + 1))
  done
  die "no free docker subnet in the demo pool (10.$SUBNET_POOL_FROM.0.0/16 .. 10.$SUBNET_POOL_TO.255.0/24)"
}

load_env() { # sets MESH_SUBNET, ALICE_IP, BOB_IP, CHARLIE_IP from $ENV_FILE
  [ -f "$ENV_FILE" ] || return 1
  # shellcheck disable=SC1090
  . "$ENV_FILE"
  [ -n "${MESH_SUBNET:-}" ] && [ -n "${ALICE_IP:-}" ] && [ -n "${BOB_IP:-}" ] && [ -n "${CHARLIE_IP:-}" ] || return 1
  return 0
}

write_env() { # <subnet>
  local subnet="$1" node
  {
    echo "# Generated by demo/generate-configs.sh — edit demo/docker-compose.yml or rerun with --force."
    echo "MESH_SUBNET=$subnet"
    for node in $NODES; do
      echo "$(upper "$node")_IP=$(subnet_host_ip "$subnet" "$(host_octet "$node")")"
    done
  } >"$ENV_FILE"
}

# ── Route table ──────────────────────────────────────────────────────
# Next hop toward $TARGET_PREFIX as the daemon itself sees it (jq runs inside the image).
nh() { # <node>
  docker exec "$(container "$1")" sh -c \
    "nylon status --json -i nylon0 | jq -r '.status.routes.forward[]? | select(.prefix==\"$TARGET_PREFIX\") | .nh'" \
    2>/dev/null | head -1 || true
}

# Has <node> been told about the path to $TARGET_ID through $BACKUP_ID? The daemon
# advertises that alternative next to the direct route, and a failover is only
# quick when it is already known — otherwise the mesh first has to notice the
# link death and wait for the next route update (~45s instead of ~5s).
has_standby() { # <node>
  docker exec "$(container "$1")" sh -c \
    "nylon status --json -i nylon0 | jq -e --arg p $TARGET_PREFIX --arg n $BACKUP_ID 'any(.status.neighbours[]?; .peerId == \$n and any(.routes[]?; .pubRoute.source.prefix == \$p))' >/dev/null" \
    2>/dev/null
}

# Bring the mesh into that state with one cut/restore cycle, before anything is
# recorded or handed over: a mesh that has been up for a while has been through a
# reconvergence, and only then does the algorithm accept the backup route. Leave
# the stand converged again afterwards.
warm_up() { # <timeout_s>
  local target_ip timeout="${1:-120}"
  target_ip="$(subnet_host_ip "$MESH_SUBNET" "$(host_octet "$TARGET_ID")")"
  info "warming the mesh up with one cut/restore cycle"
  docker exec "$(container alice)" iptables -A INPUT -s "$target_ip" -j DROP
  docker exec "$(container alice)" iptables -A OUTPUT -d "$target_ip" -j DROP
  wait_for_nh alice "$BACKUP_ID" "$timeout"
  docker exec "$(container alice)" iptables -F
  wait_for_nh alice "$TARGET_ID" "$timeout"
  info "mesh warmed up (backup path known to alice: $(has_standby alice && echo yes || echo no))"
}

# The stand's topology depends on alice's link shaping (see generate-configs.sh).
# pre_up failures are only logged by the daemon, so check that it actually landed
# instead of recording a mesh that is about to oscillate.
wait_for_shaping() { # <timeout_s>
  local deadline got
  deadline=$(($(date +%s) + ${1:-30}))
  while :; do
    got="$(docker exec "$(container alice)" tc qdisc show dev eth0 2>/dev/null || true)"
    case "$got" in
    *netem*) return 0 ;;
    esac
    if [ "$(date +%s)" -ge "$deadline" ]; then
      dc logs --tail=50 >&2 || true
      die "alice's link shaping is missing — check pre_up in $CONFIGS_DIR/alice.yaml"
    fi
    sleep 1
  done
}

wait_for_nh() { # <node> <expected> <timeout_s>
  local node="$1" expected="$2" timeout="$3" got deadline
  deadline=$(($(date +%s) + timeout))
  info "waiting for $node's next hop toward $TARGET_PREFIX to become '$expected' (≤${timeout}s)"
  while :; do
    got="$(nh "$node")"
    if [ "$got" = "$expected" ]; then
      return 0
    fi
    if [ "$(date +%s)" -ge "$deadline" ]; then
      echo >&2
      dc logs --tail=100 >&2 || true
      die "$node's next hop toward $TARGET_PREFIX is '${got:-unknown}', expected '$expected' after ${timeout}s"
    fi
    sleep 1
  done
}
